# Generated by Django 3.0.2 on 2020-08-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.TextField(max_length=10000),
        ),
    ]
