# Generated by Django 3.0.2 on 2020-08-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200818_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='favourite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
