# Generated by Django 3.0.2 on 2020-08-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200818_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
