# Generated by Django 3.0.2 on 2020-08-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200818_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.TextField(default='https://yt3.ggpht.com/iMT9MVrt6qxAfTxeKUX17ESdppsDntW2eA9YvnONcPqxlbdt9SkVhaIRsAtE0PFqRiLA-arexQ=s900-c-k-c0xffffffff-no-rj-mo', max_length=10000),
        ),
    ]
